#!/bin/sh

#
# Copyright 2018, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(DATA61_GPL)
#

#
# Template for custom init script for guest linux
# that loads some additional kernel modules.
#
# __LINUX_VERSION__ is used as a placeholder for the linux version
# number triple (e.g. "4.7.2").

# devtmpfs does not get automounted for initramfs
/bin/mount -t devtmpfs devtmpfs /dev
exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console

insmod /lib/modules/4.8.16/kernel/drivers/vmm/connection.ko


# VFAT FS kernel module synthesised from Cogent
#insmod /lib/modules/__LINUX_VERSION__/kernel/drivers/vfat/cg-fat.ko
#insmod /lib/modules/__LINUX_VERSION__/kernel/drivers/vfat/cg-vfat.ko

exec /sbin/init $*
